### ISSUE TITLE
cannot configure connections in lenses v5

### ISSUE THREAD

**Issue by rotarur** [lensesio/lenses-helm-charts#13]
I'm having this error when configuring connections in lenses v5:

```
cannot decode Connections, expected a map
```

the lenses provisioner is failing and the deployment is in error state.

I'm copying the default configs from this doc https://docs.lenses.io/5.0/configuration/dynamic/connect/ even though I'm having the issue.

Here is my config:

```
lenses:
    provision:
      enabled: true
      yaml:
        connections:
          kafka:
            tags: [ "kafka" ]
            templateName: KafkaConnect
            configurationObject:
              workers:
                - http://broker-1:8083
                - http://broker-2:8083
                - http://broker-3:8083
              # all metrics properties are optional
              metricsPort: 9581
              metricsType: JMX
              metricsSsl: false
```
