### ISSUE TITLE
Pulling image from private registry fails in helm chart v5.0.0

### ISSUE THREAD

**Issue by vaidx** [lensesio/lenses-helm-charts#14]
When I try to pull the lenses.io image from my private registry, I receive the following message:

```
Error: unable to build kubernetes objects from release manifest: error validating "": error validating data: ValidationError(Deployment.spec.template.spec.containers[0]): unknown field "imagePullSecrets" in io.k8s.api.core.v1.Container
```

Excerpt from values.yaml file:
```
image:
  repository: lensesio/lenses
  pullPolicy: IfNotPresent
  tag: 5.0.0
  registrySecretKey: secret-key

```
  
 I believe this is due to the incorrect placement of imagePullSecrets field in the deployment.yaml in Helm Chart.

```
      containers:
      - name: {{ .Chart.Name }}
        image: {{include "lensesImage" . | quote }}
        {{- if .Values.image.registrySecretKey }}
        imagePullSecrets:
          - name: {{ .Values.image.registrySecretKey }}
        {{- end }}
        imagePullPolicy: {{ .Values.image.pullPolicy }}
```
