### ISSUE TITLE
support for ingressClass missing

### ISSUE THREAD

**Issue by smartbit** [lensesio/lenses-helm-charts#8]
New nginx-ingress 1.0 doesn't support the [deprecated Ingress Annotations](https://kubernetes.io/docs/concepts/services-networking/ingress/#deprecated-annotation) anymore

> from version 1.0.0 of the Ingress-NGINX Controller, a `ingressclass` object is **required**.

[Ingress Nginx documentation](https://kubernetes.github.io/ingress-nginx/#what-is-an-ingressclass-and-why-is-it-important-for-users-of-ingress-nginx-controller-now)

> continue supporting Kubernetes versions older than 1.22 with Ingress-NGINX version 0.47.0.

From blog [Updating NGINX-Ingress to use the stable Ingress API](https://kubernetes.io/blog/2021/07/26/update-with-ingress-nginx/)

The helm Chart of lenses seems not to support the [ingressClassName](https://kubernetes.io/docs/concepts/services-networking/ingress/#ingress-class), can you please add support for `ingressclass` object?

**Comment by smartbit** [comment]
@georgeyord Thank you for [adding](https://github.com/lensesio/lenses-helm-charts/commit/7b28a37d0318d1419e2d8f7d3d9f731a0457ddcf) the `ingressClassName`.

The change doesn't remove `kubernetes.io/ingress.class` type from the [ingress annotations](https://github.com/lensesio/lenses-helm-charts/blob/release/4.3/charts/lenses/templates/ingress.yaml#L17-L20). To make it work on an ingress other than [traefik](https://github.com/lensesio/lenses-helm-charts/blob/release/4.3/charts/lenses/values.yaml#L112), we **must** disable all annotations with `lenses.ingress.annotations: []`  and can **not** add additional annotations eg for acme:

```yaml
  ingress:
    enabled: true
    ingressClassName: nginx
    annotations:
      cert-manager.io/cluster-issuer: ca-issuer
``` 

Possible solution directions:
1. IMHO easiest would be **removing** the default annotation `kubernetes.io/ingress.class: traefik` from [values.yaml](https://github.com/lensesio/lenses-helm-charts/blob/release/4.3/charts/lenses/values.yaml#L112)
  ```yaml
    # Ingress annotations
    annotations:
      kubernetes.io/ingress.class: traefik
  ```

2. Alternatively the helm code can test the support of `ingressClassName` (using [semverCompare](https://helm.sh/docs/chart_template_guide/function_list/#semvercompare)?) on the cluster and act accordingly.
